http.host: "0.0.0.0"
xpack.monitoring.enabled: false # Disabled for AWS ElasticSearch Services
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
# xpack.monitoring.elasticsearch.hosts: [ "https://elasticsearch.aws.vpc.endpoint:443" ]
log.level: info
